### ISSUE TITLE
Handle empty responses from Open Subtitles

### ISSUE THREAD

**Issue by js-kyle** [UniversalMediaServer/api#20]
Sometimes if open subtitles can't find metadata based on a specific hash it will return an empty response - how should that be handled?

Options:

- [ ] create the empty record, so subsequent lookups return empty db documents
- [ ] avoid creating the incomplete document

**Comment by SubJunk** [comment]
My thoughts are that failed lookups should enter an in-between state where we return a failed lookup to the UMS client, and add the query to another table for failures that get retried periodically. Each failed lookup could get retried say once a month in case it got added. I think at the moment, it's the failed lookups that are causing the most spam from UMS to the OpenSubs API, since the client just keeps trying every time it starts

**Comment by SubJunk** [comment]
@js-kyle another approach I've been thinking about is instead of having it on a timer, it ties in with the lookup cycle, so if UMS requests metadata for a video and we don't have it in our database, we check our failed lookups collection. If the entry is already in the failed lookups collection, we check the last time it was tried. If it was tried over a month(?) ago, we look for it on OpenSubs, else we return 0 results.

**Comment by js-kyle** [comment]
Done
